### PR TITLE
Add CRUD support for register limit APIs

### PR DESCRIPTION
**Pull request by konan-abhi**
[docs](https://docs.openstack.org/api-ref/identity/v3/#unified-limits)
 [code](https://github.com/openstack/keystone/blob/master/keystone/api/registered_limits.py#L49)

### CODE REVIEW

**Comment by mandre** [comment]
@konan-abhi is this ready for review? Otherwise, I suggest you mark your PR as draft while you're still working on it.

**Comment by konan-abhi** [comment]
> @konan-abhi is this ready for review? Otherwise, I suggest you mark your PR as draft while you're still working on it.



> @konan-abhi is this ready for review? Otherwise, I suggest you mark your PR as draft while you're still working on it.

Hi @mandre I am struggling to fix unit tests (since not able to run/debug them locally). Any inputs there will be helpful. Other than that I think functional and other tests are working as expected and yes apart from unittests failure the patch is ready for review.

File: openstack/identity/v3/registered_limits/testing/fixtures.go [hunk 1]
```diff
@@ -0,0 +1,219 @@
...
+{
+    "links": {
+        "self": "http://10.3.150.25/identity/v3/registered_limits",
+        "previous": null,
+        "next": null
+    },
+    "registered_limits": [
+        {
+            "resource_name": "volume",
+            "region_id": RegionOne,
```
Comment (mandre) [inline openstack/identity/v3/registered_limits/testing/fixtures.go:24]: The `"invalid character 'R' looking for beginning of value"` you [see in the unit tests](https://github.com/gophercloud/gophercloud/actions/runs/4978055778/jobs/8907869530?pr=2616#step:6:138) comes from missing quotes around `RegionOne`.

File: openstack/identity/v3/registered_limits/testing/fixtures.go [hunk 2]
```diff
@@ -0,0 +1,219 @@
...
+}
+`
+
+// UpdateOutput provides an Update response.
+const UpdateOutput = `
+{
+    "registered_limit": {
+        "id": "3229b3849f584faea483d6851f7aab05",
+        "service_id": "9408080f1970482aa0e38bc2d4ea34b7",
+        "region_id": RegionOne,
```
Comment (mandre) [inline openstack/identity/v3/registered_limits/testing/fixtures.go:104]: Here too, you're missing quotes.

File: openstack/identity/v3/registered_limits/testing/fixtures.go [hunk 3]
```diff
@@ -0,0 +1,219 @@
...
+        }
+    ]
+}
+`
+
+// GetOutput provides a Get result.
+const GetOutput = `
+{
+    "registered_limit": {
+        {
```
Comment (mandre) [inline openstack/identity/v3/registered_limits/testing/fixtures.go:52]: Here you're have one too many level of curly braces, that's why you're seeing the `"invalid character '{' looking for beginning of object key string"` error [in the unit tests](https://github.com/gophercloud/gophercloud/actions/runs/4978055778/jobs/8907869530?pr=2616#step:6:144).

**Review by mandre — COMMENTED** [review]
> Hi @mandre I am struggling to fix unit tests (since not able to run/debug them locally). Any inputs there will be helpful. Other than that I think functional and other tests are working as expected and yes apart from unittests failure the patch is ready for review.

Contrary to acceptance tests, you don't need a live environment to run the unit tests. You can run them locally with:
```
go test -v ./openstack/identity/v3/registered_limits/testing
```

That should make it easier to fix the unit tests.

I've pointed to the errors that are currently reported, but there a few more.

**Comment by nikParasyr** [comment]
This should close https://github.com/gophercloud/gophercloud/issues/2290, or partially implement. Just linking the PR with the issue

File: openstack/identity/v3/registered_limits/testing/fixtures.go (hunk 2 above)
Comment (konan-abhi) [reply openstack/identity/v3/registered_limits/testing/fixtures.go]: Done

**Comment by konan-abhi** [comment]
Does the failure in unit test means missing acceptance test for Get call?

**Comment by mandre** [comment]
> Does the failure in unit test means missing acceptance test for Get call?

It complains that the comment doesn't follow go formatting.
You need to run `go fmt` on `openstack/identity/v3/registered_limits/doc.go`, using go 1.19+.

**Comment by fmount** [comment]
> > Does the failure in unit test means missing acceptance test for Get call?
> 
> It complains that the comment doesn't follow go formatting. You need to run `go fmt` on `openstack/identity/v3/registered_limits/doc.go`, using go 1.19+.

I also see the unit tests failing:

```
Error: /home/runner/go/pkg/mod/golang.org/x/tools@v0.9.1/internal/gocommand/invoke.go:381:62: undefined: os.ErrProcessDone
note: module requires Go 1.18
Error: Process completed with exit code 2.
```
@mandre any particular reason to stay on 1.14 ?

**Comment by fmount** [comment]
In general the patch passes locally:

```
> go test -v ./openstack/identity/v3/registered_limits/testing
=== RUN   TestListRegisteredLimits
--- PASS: TestListRegisteredLimits (0.00s)
=== RUN   TestListRegisteredLimitsAllPages
--- PASS: TestListRegisteredLimitsAllPages (0.00s)
=== RUN   TestCreateRegisteredLimits
--- PASS: TestCreateRegisteredLimits (0.00s)
=== RUN   TestGetRegisteredLimit
--- PASS: TestGetRegisteredLimit (0.00s)
=== RUN   TestDeleteRegisteredLimit
--- PASS: TestDeleteRegisteredLimit (0.00s)
=== RUN   TestUpdateRegisteredLimit
--- PASS: TestUpdateRegisteredLimit (0.00s)
PASS
ok      github.com/gophercloud/gophercloud/openstack/identity/v3/registered_limits/testing      0.005s

```
I suspect we should address something related to the CI (functional-identity tests instead are failing for unrelated issues)

**Comment by konan-abhi** [comment]
Ready for review!

**Comment by mandre** [comment]
> I also see the unit tests failing:
> 
> ```
> Error: /home/runner/go/pkg/mod/golang.org/x/tools@v0.9.1/internal/gocommand/invoke.go:381:62: undefined: os.ErrProcessDone
> note: module requires Go 1.18
> Error: Process completed with exit code 2.
> ```
>
> @mandre any particular reason to stay on 1.14 ?

Right, the 1.14 unit test job started failing recently because a dependency of `goimport` now requires go 1.18. I think for now we'll pin `goimport` to a version that works with go 1.14 and bump our minimal go version on our next major version.

**Comment by fmount** [comment]
Nice! I think CI is happy now (`semver` should probably be assigned by maintainers), but I think the patch is ready for review.
The behavior is pretty similar to the existing `limits`, so we should be on the right path as long as the style/approach is approved.

**Comment by mandre** [comment]
Ack. I can review the PR next week at the earliest.

File: openstack/identity/v3/registered_limits/requests.go [hunk 4]
```diff
@@ -0,0 +1,159 @@
+package registered_limits
```
Comment (nikParasyr) [inline openstack/identity/v3/registered_limits/requests.go:1]: Shouldn't the package be `registeredlimits`. I don't recall any gohpercloud package to have `_` or any other seperator. It's typically lower case and no seperator. @mandre ?

File: openstack/identity/v3/registered_limits/requests.go [hunk 5]
```diff
@@ -0,0 +1,159 @@
...
+	Description *string `json:"description,omitempty"`
+
+	// DefaultLimit is the override limit.
+	DefaultLimit *int `json:"default_limit,omitempty"`
+
+	// RegionID is the ID of the region where the limit is applied.
+	RegionID string `json:"region_id,omitempty"`
+
+	// ServiceID is the ID of the service where the limit is applied.
+	ServiceID string `json:"service_id" required:"true"`
```
Comment (nikParasyr) [inline openstack/identity/v3/registered_limits/requests.go:129]: this shouldnt be `required` based on docs.

I do read this on docs though:
> Either service_id, resource_name, or region_id must be different than existing value otherwise it will raise 409.

And i have 0 clue why they have added this restriction, nor why they allow updates on ServiceID or ResourceName... :man_shrugging:

Comment (konan-abhi) [reply openstack/identity/v3/registered_limits/requests.go:129]: Same, I don't have clue as well. I think this is global default limit across all the projects and if you want different limit for particular service then you can override it by "limit" api. (This is my guess though)

Comment (konan-abhi) [reply openstack/identity/v3/registered_limits/requests.go]: Local acceptance test results;


=== RUN   TestRegisteredLimitsList
--- PASS: TestRegisteredLimitsList (0.14s)
=== RUN   TestCreateRegisteredLimits
--- PASS: TestCreateRegisteredLimits (0.33s)
=== RUN   TestRegisteredLimitsCRUD
    tools.go:80: {
          "id": "f71aca4f1d82428488ee230a9ee123a4",
          "region_id": "RegionOne",
          "service_id": "4da42dd1adf54bbb878d925fc64382da",
          "description": "TESTLIMITS-DESC-Zs7SnB5c",
          "resource_name": "LIMIT-NAME-t22jpMnh",
          "default_limit": 55,
          "links": {
            "self": "http://10.0.108.117/identity/v3/registered_limits/f71aca4f1d82428488ee230a9ee123a4"
          }
        }
    tools.go:80: {
          "id": "f71aca4f1d82428488ee230a9ee123a4",
          "region_id": "RegionOne",
          "service_id": "4da42dd1adf54bbb878d925fc64382da",
          "description": "TESTLIMITS-DESC-Zs7SnB5c",
          "resource_name": "LIMIT-NAME-t22jpMnh",
          "default_limit": 55,
          "links": {
            "self": "http://10.0.108.117/identity/v3/registered_limits/f71aca4f1d82428488ee230a9ee123a4"
          }
        }
    tools.go:80: {
          "id": "f71aca4f1d82428488ee230a9ee123a4",
          "region_id": "RegionOne",
          "service_id": "4da42dd1adf54bbb878d925fc64382da",
          "description": "Test description for registered limit",
          "resource_name": "LIMIT-NAME-MyZR9stf",
          "default_limit": 1000,
          "links": {
            "self": "http://10.0.108.117/identity/v3/registered_limits/f71aca4f1d82428488ee230a9ee123a4"
          }
        }
--- PASS: TestRegisteredLimitsCRUD (0.59s)



Local Unit test results;
go test -v ./openstack/identity/v3/registeredlimits/testing
=== RUN   TestListRegisteredLimits
--- PASS: TestListRegisteredLimits (0.00s)
=== RUN   TestListRegisteredLimitsAllPages
--- PASS: TestListRegisteredLimitsAllPages (0.00s)
=== RUN   TestCreateRegisteredLimits
--- PASS: TestCreateRegisteredLimits (0.00s)
=== RUN   TestGetRegisteredLimit
--- PASS: TestGetRegisteredLimit (0.00s)
=== RUN   TestDeleteRegisteredLimit
--- PASS: TestDeleteRegisteredLimit (0.00s)
=== RUN   TestUpdateRegisteredLimit
--- PASS: TestUpdateRegisteredLimit (0.00s)
PASS
ok  	github.com/gophercloud/gophercloud/openstack/identity/v3/registeredlimits/testing	0.009s

File: openstack/identity/v3/registeredlimits/requests.go [hunk 6]
```diff
@@ -0,0 +1,160 @@
...
+	ServiceID string `json:"service_id" required:"true"`
+
+	// Description of the limit.
+	Description string `json:"description,omitempty"`
+
+	// ResourceName is the name of the resource that the limit is applied to.
+	ResourceName string `json:"resource_name" required:"true"`
+
+	// DefaultLimit is the default limit.
+	DefaultLimit int `json:"default_limit"`
```
[the remark this answers is not in the document]
Comment (konan-abhi) [reply openstack/identity/v3/registeredlimits/requests.go:67]: Done

File: acceptance/openstack/identity/v3/registeredlimits_test.go [hunk 7]
```diff
@@ -0,0 +1,162 @@
...
+	clients.SkipReleasesBelow(t, "stable/xena")
+
+	limitDescription := tools.RandomString("TESTLIMITS-DESC-", 8)
+	defaultLimit := tools.RandomInt(1, 100)
+	resourceName := tools.RandomString("LIMIT-NAME-", 8)
+
+	client, err := clients.NewIdentityV3Client()
+	th.AssertNoErr(t, err)
+
+	// Find image service (glance on Devstack)
```
[the remark this answers is not in the document]
Comment (konan-abhi) [reply acceptance/openstack/identity/v3/registeredlimits_test.go:52]: Done

File: acceptance/openstack/identity/v3/registeredlimits_test.go [hunk 8]
```diff
@@ -0,0 +1,162 @@
...
+	listOpts := registeredlimits.ListOpts{}
+
+	allPages, err := registeredlimits.List(client, listOpts).AllPages()
+	th.AssertNoErr(t, err)
+
+	_, err = registeredlimits.ExtractRegisteredLimits(allPages)
+	th.AssertNoErr(t, err)
+}
+
+func TestCreateRegisteredLimits(t *testing.T) {
```
[the remark this answers is not in the document]
Comment (konan-abhi) [reply acceptance/openstack/identity/v3/registeredlimits_test.go:37]: Done

File: acceptance/openstack/identity/v3/registeredlimits_test.go [hunk 9]
```diff
@@ -0,0 +1,162 @@
...
+	th "github.com/gophercloud/gophercloud/testhelper"
+)
+
+func TestRegisteredLimitsList(t *testing.T) {
+	err := os.Setenv("OS_SYSTEM_SCOPE", "all")
+	th.AssertNoErr(t, err)
+	defer os.Unsetenv("OS_SYSTEM_SCOPE")
+
+	clients.RequireAdmin(t)
+	clients.SkipReleasesBelow(t, "stable/xena")
```
[the remark this answers is not in the document]
Comment (konan-abhi) [reply acceptance/openstack/identity/v3/registeredlimits_test.go:23]: Done

**Comment by konan-abhi** [comment]
Ready for review!

**Review by mandre — APPROVED** [review]

**Comment by konan-abhi** [comment]
@mandre Thank you for review, may I know when we can expect the release of 1.4.0? Our new development work depends on this new release.

Thank you!

**Comment by mandre** [comment]
> @mandre Thank you for review, may I know when we can expect the release of 1.4.0? Our new development work depends on this new release.

We don't know yet when we'll release 1.4.0, probably in not too long.

In the meantime, you may want to depend on the master branch, or on a fork that you control.

**Comment by fmount** [comment]
> > @mandre Thank you for review, may I know when we can expect the release of 1.4.0? Our new development work depends on this new release.
> 
> We don't know yet when we'll release 1.4.0, probably in not too long.
> 
> In the meantime, you may want to depend on the master branch, or on a fork that you control.

Thanks @mandre for the input, do you have general timeline that is usually followed as a general rule when bumping from a tag to the next one?

**Comment by mandre** [comment]
> Thanks @mandre for the input, do you have general timeline that is usually followed as a general rule when bumping from a tag to the next one?

There's no strict rule, it generally depends on whether there's activity in the open PRs, and how long since the last tag. We try to release every other month.

**Comment by mandre** [comment]
@konan-abhi @fmount FYI, there's now [a v1.4.0 version](https://github.com/gophercloud/gophercloud/releases/tag/v1.4.0) that includes your change.

**Comment by konan-abhi** [comment]
Thank you very much!!
